CREATE TABLE if NOT EXISTS student
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(30) NOT NULL UNIQUE,
    email VARCHAR(150)
);

CREATE TABLE If NOT EXISTS COURSE
(
    id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
  	studentList SERIAL,
  	FOREIGN KEY(studentList) REFERENCES student(id)
);

